# Development Configuration
# Use this for local development with: zola serve --config config.dev.toml

# The URL the site will be built for (localhost for development)
base_url = "/"

# Site title and description
title = "Clexp Explores Technology"
description = "Technical blog about networking, system administration, and home lab adventures"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
# The search index format - use elasticlunr_javascript for client-side search
index_format = "elasticlunr_javascript"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here 